storage_dir:
  publika: "data/pages/publika/"
  timpul: "data/pages/timpul/"
  unimedia: "data/pages/unimedia/"
  pro_tv: "data/pages/protv/"
  agora: "data/pages/agora/"
  prime: "data/pages/prime/"
